### ISSUE TITLE
loop and space dont work

### ISSUE THREAD

**Issue by scottsmith8** [graykick/react-marquee-double#4]
loop={false}
space={100}

these props seems to have no effect

<MarqueeDouble
                            step={1} interval={20}
                            autoStart={true}
                            direction={'left'}
                            loop={false}
                            space={100}
                            delay={2000}>
                            {this.state.nextMsg}
</MarqueeDouble>}

**Comment by graykick** [comment]
I am sorry that I am late. I will fix it.

**Comment by graykick** [comment]
I fixed the loop issue.

If you do not want to loop, set loop `0`. like below.
Or, If you want to loop infinitely, set `-1`.
Or, If you specify a specific number, It loops that much.
```JSX
<MarqueeDouble
    step={1} interval={20}
    autoStart={true}
    direction={'left'}
    loop={0} // -1 is infinite, 0 is not flow
    space={100}
    delay={2000}>
   {this.state.nextMsg}
}
```

**Comment by graykick** [comment]
space is working well.

Check this demo.
https://repl.it/@graykick/react-marquee-double-DEMO
![image](https://user-images.githubusercontent.com/17001199/52859719-c738d700-3170-11e9-870e-10a4aff41113.png)
