### ISSUE TITLE
not working with next js

### ISSUE THREAD

**Issue by victororlyk** [graykick/react-marquee-double#5]
When i try to use it i have an issue version *"react-marquee-double": "^0.2.0",*

```
es/react-marquee-double/App.css:2
.MarqueeC-Div {
^

SyntaxError: Unexpected token .
```

code is below
```javascript
class MarqueeLines extends Component {
  render() {
    const {placement} = this.props;
    const text = 'Text '.repeat(60).split(' ');
    const display = () =>{
      return  text.map((value, index)=>(
        <span className="item" key={index}>{value}</span>
      ))
    };
    return (
      <StyledMarqueContainer className={placement}>
        <MarqueeDouble
          ref={(ref) => {this.marquee = ref}}
          step={1}
          interval={20}
          autoStart
          direction="left"
          delay={0}
          onStart={()=>{this.marquee.delay()}}>
          <div>{display()}</div>
        </MarqueeDouble>
      </StyledMarqueContainer>
    );
  }
}
```

**Comment by graykick** [comment]
Sorry for the late reply. I am new to next.js
But I found a solution.

This is an issue about importing CSS module in next.js.
You need [@zeit/next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css) module and some configuration.
Put following code as `next.config.js` in root of project folder.
### next.config.js
```
if (typeof require !== 'undefined') {
  require.extensions['.less'] = () => {};
  require.extensions['.css'] = file => {};
}

const withCSS = require('@zeit/next-css');

module.exports = withCSS();
```


This is my working sandbox example with next and react-marquee-double.
https://codesandbox.io/s/nextjs-blog-post-example-ndrvj

If you solved the problem, please close this issue.

### Reference
- https://github.com/zeit/next-plugins/issues/266#issuecomment-474721942
- https://stackoverflow.com/questions/57503627/next-js-project-has-trouble-loading-css-from-aws-amplify
